#define INTERACT_CAN_SCREW		1
#define INTERACT_CAN_PRY		2
#define INTERACT_CAN_CUT		4
#define INTERACT_CAN_WELD		8
#define INTERACT_CAN_SHOVEL 	16
#define INTERACT_CAN_HAMMER 	32
#define INTERACT_CAN_WRENCH 	64
#define INTERACT_CAN_WRENCH 	128